import STARRED_REPOSITORIES from '../constants';
import { RepositoryType } from '../types';

const repositorySet: { [index: string]: any } = {
  wideData: [
    {
      id: 78483432,
      node_id: 'MDEwOlJlcG9zaXRvcnk3ODQ4MzQzMg==',
      name: 'TranslucentTB',
      full_name: 'TranslucentTB/TranslucentTB',
      private: false,
      owner: {
        login: 'TranslucentTB',
        id: 25557326,
        node_id: 'MDEyOk9yZ2FuaXphdGlvbjI1NTU3MzI2',
        avatar_url: 'https://avatars.githubusercontent.com/u/25557326?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/TranslucentTB',
        html_url: 'https://github.com/TranslucentTB',
        followers_url: 'https://api.github.com/users/TranslucentTB/followers',
        following_url: 'https://api.github.com/users/TranslucentTB/following{/other_user}',
        gists_url: 'https://api.github.com/users/TranslucentTB/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/TranslucentTB/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/TranslucentTB/subscriptions',
        organizations_url: 'https://api.github.com/users/TranslucentTB/orgs',
        repos_url: 'https://api.github.com/users/TranslucentTB/repos',
        events_url: 'https://api.github.com/users/TranslucentTB/events{/privacy}',
        received_events_url: 'https://api.github.com/users/TranslucentTB/received_events',
        type: 'Organization',
        site_admin: false,
      },
      html_url: 'https://github.com/TranslucentTB/TranslucentTB',
      description: 'A lightweight utility that makes the Windows taskbar translucent/transparent.',
      fork: false,
      url: 'https://api.github.com/repos/TranslucentTB/TranslucentTB',
      forks_url: 'https://api.github.com/repos/TranslucentTB/TranslucentTB/forks',
      keys_url: 'https://api.github.com/repos/TranslucentTB/TranslucentTB/keys{/key_id}',
      collaborators_url: 'https://api.github.com/repos/TranslucentTB/TranslucentTB/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/TranslucentTB/TranslucentTB/teams',
      hooks_url: 'https://api.github.com/repos/TranslucentTB/TranslucentTB/hooks',
      issue_events_url: 'https://api.github.com/repos/TranslucentTB/TranslucentTB/issues/events{/number}',
      events_url: 'https://api.github.com/repos/TranslucentTB/TranslucentTB/events',
      assignees_url: 'https://api.github.com/repos/TranslucentTB/TranslucentTB/assignees{/user}',
      branches_url: 'https://api.github.com/repos/TranslucentTB/TranslucentTB/branches{/branch}',
      tags_url: 'https://api.github.com/repos/TranslucentTB/TranslucentTB/tags',
      blobs_url: 'https://api.github.com/repos/TranslucentTB/TranslucentTB/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/TranslucentTB/TranslucentTB/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/TranslucentTB/TranslucentTB/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/TranslucentTB/TranslucentTB/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/TranslucentTB/TranslucentTB/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/TranslucentTB/TranslucentTB/languages',
      stargazers_url: 'https://api.github.com/repos/TranslucentTB/TranslucentTB/stargazers',
      contributors_url: 'https://api.github.com/repos/TranslucentTB/TranslucentTB/contributors',
      subscribers_url: 'https://api.github.com/repos/TranslucentTB/TranslucentTB/subscribers',
      subscription_url: 'https://api.github.com/repos/TranslucentTB/TranslucentTB/subscription',
      commits_url: 'https://api.github.com/repos/TranslucentTB/TranslucentTB/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/TranslucentTB/TranslucentTB/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/TranslucentTB/TranslucentTB/comments{/number}',
      issue_comment_url: 'https://api.github.com/repos/TranslucentTB/TranslucentTB/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/TranslucentTB/TranslucentTB/contents/{+path}',
      compare_url: 'https://api.github.com/repos/TranslucentTB/TranslucentTB/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/TranslucentTB/TranslucentTB/merges',
      archive_url: 'https://api.github.com/repos/TranslucentTB/TranslucentTB/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/TranslucentTB/TranslucentTB/downloads',
      issues_url: 'https://api.github.com/repos/TranslucentTB/TranslucentTB/issues{/number}',
      pulls_url: 'https://api.github.com/repos/TranslucentTB/TranslucentTB/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/TranslucentTB/TranslucentTB/milestones{/number}',
      notifications_url: 'https://api.github.com/repos/TranslucentTB/TranslucentTB/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/TranslucentTB/TranslucentTB/labels{/name}',
      releases_url: 'https://api.github.com/repos/TranslucentTB/TranslucentTB/releases{/id}',
      deployments_url: 'https://api.github.com/repos/TranslucentTB/TranslucentTB/deployments',
      created_at: '2017-01-10T00:53:17Z',
      updated_at: '2024-03-25T18:09:54Z',
      pushed_at: '2024-03-03T10:20:23Z',
      git_url: 'git://github.com/TranslucentTB/TranslucentTB.git',
      ssh_url: 'git@github.com:TranslucentTB/TranslucentTB.git',
      clone_url: 'https://github.com/TranslucentTB/TranslucentTB.git',
      svn_url: 'https://github.com/TranslucentTB/TranslucentTB',
      homepage: '',
      size: 11596,
      stargazers_count: 13996,
      watchers_count: 13996,
      language: 'C++',
      has_issues: true,
      has_projects: false,
      has_downloads: true,
      has_wiki: false,
      has_pages: false,
      has_discussions: false,
      forks_count: 1064,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 128,
      license: {
        key: 'gpl-3.0',
        name: 'GNU General Public License v3.0',
        spdx_id: 'GPL-3.0',
        url: 'https://api.github.com/licenses/gpl-3.0',
        node_id: 'MDc6TGljZW5zZTk=',
      },
      allow_forking: true,
      is_template: false,
      web_commit_signoff_required: false,
      topics: [
        'acrylic',
        'aero',
        'blur',
        'customization',
        'discord',
        'fluent-design',
        'gitter',
        'taskbar',
        'undocumented',
        'windows',
        'windows-10',
      ],
      visibility: 'public',
      forks: 1064,
      open_issues: 128,
      watchers: 13996,
      default_branch: 'release',
      score: 1,
    },
    {
      id: 78544867,
      node_id: 'MDEwOlJlcG9zaXRvcnk3ODU0NDg2Nw==',
      name: 'awesome-github-wechat-weapp',
      full_name: 'opendigg/awesome-github-wechat-weapp',
      private: false,
      owner: {
        login: 'opendigg',
        id: 23257329,
        node_id: 'MDQ6VXNlcjIzMjU3MzI5',
        avatar_url: 'https://avatars.githubusercontent.com/u/23257329?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/opendigg',
        html_url: 'https://github.com/opendigg',
        followers_url: 'https://api.github.com/users/opendigg/followers',
        following_url: 'https://api.github.com/users/opendigg/following{/other_user}',
        gists_url: 'https://api.github.com/users/opendigg/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/opendigg/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/opendigg/subscriptions',
        organizations_url: 'https://api.github.com/users/opendigg/orgs',
        repos_url: 'https://api.github.com/users/opendigg/repos',
        events_url: 'https://api.github.com/users/opendigg/events{/privacy}',
        received_events_url: 'https://api.github.com/users/opendigg/received_events',
        type: 'User',
        site_admin: false,
      },
      html_url: 'https://github.com/opendigg/awesome-github-wechat-weapp',
      description: '微信小程序开源项目库汇总',
      fork: false,
      url: 'https://api.github.com/repos/opendigg/awesome-github-wechat-weapp',
      forks_url: 'https://api.github.com/repos/opendigg/awesome-github-wechat-weapp/forks',
      keys_url: 'https://api.github.com/repos/opendigg/awesome-github-wechat-weapp/keys{/key_id}',
      collaborators_url: 'https://api.github.com/repos/opendigg/awesome-github-wechat-weapp/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/opendigg/awesome-github-wechat-weapp/teams',
      hooks_url: 'https://api.github.com/repos/opendigg/awesome-github-wechat-weapp/hooks',
      issue_events_url: 'https://api.github.com/repos/opendigg/awesome-github-wechat-weapp/issues/events{/number}',
      events_url: 'https://api.github.com/repos/opendigg/awesome-github-wechat-weapp/events',
      assignees_url: 'https://api.github.com/repos/opendigg/awesome-github-wechat-weapp/assignees{/user}',
      branches_url: 'https://api.github.com/repos/opendigg/awesome-github-wechat-weapp/branches{/branch}',
      tags_url: 'https://api.github.com/repos/opendigg/awesome-github-wechat-weapp/tags',
      blobs_url: 'https://api.github.com/repos/opendigg/awesome-github-wechat-weapp/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/opendigg/awesome-github-wechat-weapp/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/opendigg/awesome-github-wechat-weapp/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/opendigg/awesome-github-wechat-weapp/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/opendigg/awesome-github-wechat-weapp/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/opendigg/awesome-github-wechat-weapp/languages',
      stargazers_url: 'https://api.github.com/repos/opendigg/awesome-github-wechat-weapp/stargazers',
      contributors_url: 'https://api.github.com/repos/opendigg/awesome-github-wechat-weapp/contributors',
      subscribers_url: 'https://api.github.com/repos/opendigg/awesome-github-wechat-weapp/subscribers',
      subscription_url: 'https://api.github.com/repos/opendigg/awesome-github-wechat-weapp/subscription',
      commits_url: 'https://api.github.com/repos/opendigg/awesome-github-wechat-weapp/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/opendigg/awesome-github-wechat-weapp/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/opendigg/awesome-github-wechat-weapp/comments{/number}',
      issue_comment_url: 'https://api.github.com/repos/opendigg/awesome-github-wechat-weapp/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/opendigg/awesome-github-wechat-weapp/contents/{+path}',
      compare_url: 'https://api.github.com/repos/opendigg/awesome-github-wechat-weapp/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/opendigg/awesome-github-wechat-weapp/merges',
      archive_url: 'https://api.github.com/repos/opendigg/awesome-github-wechat-weapp/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/opendigg/awesome-github-wechat-weapp/downloads',
      issues_url: 'https://api.github.com/repos/opendigg/awesome-github-wechat-weapp/issues{/number}',
      pulls_url: 'https://api.github.com/repos/opendigg/awesome-github-wechat-weapp/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/opendigg/awesome-github-wechat-weapp/milestones{/number}',
      labels_url: 'https://api.github.com/repos/opendigg/awesome-github-wechat-weapp/labels{/name}',
      releases_url: 'https://api.github.com/repos/opendigg/awesome-github-wechat-weapp/releases{/id}',
      deployments_url: 'https://api.github.com/repos/opendigg/awesome-github-wechat-weapp/deployments',
      created_at: '2017-01-10T15:11:14Z',
      updated_at: '2024-03-25T12:10:21Z',
      pushed_at: '2020-08-16T11:36:42Z',
      git_url: 'git://github.com/opendigg/awesome-github-wechat-weapp.git',
      ssh_url: 'git@github.com:opendigg/awesome-github-wechat-weapp.git',
      clone_url: 'https://github.com/opendigg/awesome-github-wechat-weapp.git',
      svn_url: 'https://github.com/opendigg/awesome-github-wechat-weapp',
      homepage: 'http://www.opendigg.com/tags/wechat-app',
      size: 23,
      stargazers_count: 8679,
      watchers_count: 8679,
      language: null,
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      has_discussions: false,
      forks_count: 1830,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 11,
      license: null,
      allow_forking: true,
      is_template: false,
      web_commit_signoff_required: false,
      topics: [],
      visibility: 'public',
      forks: 1830,
      open_issues: 11,
      watchers: 8679,
      default_branch: 'master',
      score: 1,
    },
    {
      id: 78494737,
      node_id: 'MDEwOlJlcG9zaXRvcnk3ODQ5NDczNw==',
      name: 'walle',
      full_name: 'Meituan-Dianping/walle',
      private: false,
      owner: {
        login: 'Meituan-Dianping',
        id: 20238146,
        node_id: 'MDEyOk9yZ2FuaXphdGlvbjIwMjM4MTQ2',
        avatar_url: 'https://avatars.githubusercontent.com/u/20238146?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/Meituan-Dianping',
        html_url: 'https://github.com/Meituan-Dianping',
        followers_url: 'https://api.github.com/users/Meituan-Dianping/followers',
        following_url: 'https://api.github.com/users/Meituan-Dianping/following{/other_user}',
        gists_url: 'https://api.github.com/users/Meituan-Dianping/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/Meituan-Dianping/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/Meituan-Dianping/subscriptions',
        organizations_url: 'https://api.github.com/users/Meituan-Dianping/orgs',
        repos_url: 'https://api.github.com/users/Meituan-Dianping/repos',
        events_url: 'https://api.github.com/users/Meituan-Dianping/events{/privacy}',
        received_events_url: 'https://api.github.com/users/Meituan-Dianping/received_events',
        type: 'Organization',
        site_admin: false,
      },
      html_url: 'https://github.com/Meituan-Dianping/walle',
      description: 'Android Signature V2 Scheme签名下的新一代渠道包打包神器',
      fork: false,
      url: 'https://api.github.com/repos/Meituan-Dianping/walle',
      forks_url: 'https://api.github.com/repos/Meituan-Dianping/walle/forks',
      keys_url: 'https://api.github.com/repos/Meituan-Dianping/walle/keys{/key_id}',
      collaborators_url: 'https://api.github.com/repos/Meituan-Dianping/walle/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/Meituan-Dianping/walle/teams',
      hooks_url: 'https://api.github.com/repos/Meituan-Dianping/walle/hooks',
      issue_events_url: 'https://api.github.com/repos/Meituan-Dianping/walle/issues/events{/number}',
      events_url: 'https://api.github.com/repos/Meituan-Dianping/walle/events',
      assignees_url: 'https://api.github.com/repos/Meituan-Dianping/walle/assignees{/user}',
      branches_url: 'https://api.github.com/repos/Meituan-Dianping/walle/branches{/branch}',
      tags_url: 'https://api.github.com/repos/Meituan-Dianping/walle/tags',
      blobs_url: 'https://api.github.com/repos/Meituan-Dianping/walle/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/Meituan-Dianping/walle/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/Meituan-Dianping/walle/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/Meituan-Dianping/walle/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/Meituan-Dianping/walle/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/Meituan-Dianping/walle/languages',
      stargazers_url: 'https://api.github.com/repos/Meituan-Dianping/walle/stargazers',
      contributors_url: 'https://api.github.com/repos/Meituan-Dianping/walle/contributors',
      subscribers_url: 'https://api.github.com/repos/Meituan-Dianping/walle/subscribers',
      subscription_url: 'https://api.github.com/repos/Meituan-Dianping/walle/subscription',
      commits_url: 'https://api.github.com/repos/Meituan-Dianping/walle/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/Meituan-Dianping/walle/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/Meituan-Dianping/walle/comments{/number}',
      issue_comment_url: 'https://api.github.com/repos/Meituan-Dianping/walle/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/Meituan-Dianping/walle/contents/{+path}',
      compare_url: 'https://api.github.com/repos/Meituan-Dianping/walle/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/Meituan-Dianping/walle/merges',
      archive_url: 'https://api.github.com/repos/Meituan-Dianping/walle/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/Meituan-Dianping/walle/downloads',
      issues_url: 'https://api.github.com/repos/Meituan-Dianping/walle/issues{/number}',
      pulls_url: 'https://api.github.com/repos/Meituan-Dianping/walle/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/Meituan-Dianping/walle/milestones{/number}',
      notifications_url: 'https://api.github.com/repos/Meituan-Dianping/walle/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/Meituan-Dianping/walle/labels{/name}',
      releases_url: 'https://api.github.com/repos/Meituan-Dianping/walle/releases{/id}',
      deployments_url: 'https://api.github.com/repos/Meituan-Dianping/walle/deployments',
      created_at: '2017-01-10T03:39:25Z',
      updated_at: '2024-03-22T09:43:51Z',
      pushed_at: '2021-09-07T07:01:35Z',
      git_url: 'git://github.com/Meituan-Dianping/walle.git',
      ssh_url: 'git@github.com:Meituan-Dianping/walle.git',
      clone_url: 'https://github.com/Meituan-Dianping/walle.git',
      svn_url: 'https://github.com/Meituan-Dianping/walle',
      homepage: null,
      size: 528,
      stargazers_count: 6699,
      watchers_count: 6699,
      language: 'Java',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      has_discussions: false,
      forks_count: 1062,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 103,
      license: {
        key: 'apache-2.0',
        name: 'Apache License 2.0',
        spdx_id: 'Apache-2.0',
        url: 'https://api.github.com/licenses/apache-2.0',
        node_id: 'MDc6TGljZW5zZTI=',
      },
      allow_forking: true,
      is_template: false,
      web_commit_signoff_required: false,
      topics: [
        'android',
        'apk-signature-scheme-v2',
        'gradle',
        'v2signingenabled',
      ],
      visibility: 'public',
      forks: 1062,
      open_issues: 103,
      watchers: 6699,
      default_branch: 'master',
      score: 1,
    },
    {
      id: 78566876,
      node_id: 'MDEwOlJlcG9zaXRvcnk3ODU2Njg3Ng==',
      name: 'prettier-vscode',
      full_name: 'prettier/prettier-vscode',
      private: false,
      owner: {
        login: 'prettier',
        id: 25822731,
        node_id: 'MDEyOk9yZ2FuaXphdGlvbjI1ODIyNzMx',
        avatar_url: 'https://avatars.githubusercontent.com/u/25822731?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/prettier',
        html_url: 'https://github.com/prettier',
        followers_url: 'https://api.github.com/users/prettier/followers',
        following_url: 'https://api.github.com/users/prettier/following{/other_user}',
        gists_url: 'https://api.github.com/users/prettier/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/prettier/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/prettier/subscriptions',
        organizations_url: 'https://api.github.com/users/prettier/orgs',
        repos_url: 'https://api.github.com/users/prettier/repos',
        events_url: 'https://api.github.com/users/prettier/events{/privacy}',
        received_events_url: 'https://api.github.com/users/prettier/received_events',
        type: 'Organization',
        site_admin: false,
      },
      html_url: 'https://github.com/prettier/prettier-vscode',
      description: 'Visual Studio Code extension for Prettier',
      fork: false,
      url: 'https://api.github.com/repos/prettier/prettier-vscode',
      forks_url: 'https://api.github.com/repos/prettier/prettier-vscode/forks',
      keys_url: 'https://api.github.com/repos/prettier/prettier-vscode/keys{/key_id}',
      collaborators_url: 'https://api.github.com/repos/prettier/prettier-vscode/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/prettier/prettier-vscode/teams',
      hooks_url: 'https://api.github.com/repos/prettier/prettier-vscode/hooks',
      issue_events_url: 'https://api.github.com/repos/prettier/prettier-vscode/issues/events{/number}',
      events_url: 'https://api.github.com/repos/prettier/prettier-vscode/events',
      assignees_url: 'https://api.github.com/repos/prettier/prettier-vscode/assignees{/user}',
      branches_url: 'https://api.github.com/repos/prettier/prettier-vscode/branches{/branch}',
      tags_url: 'https://api.github.com/repos/prettier/prettier-vscode/tags',
      blobs_url: 'https://api.github.com/repos/prettier/prettier-vscode/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/prettier/prettier-vscode/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/prettier/prettier-vscode/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/prettier/prettier-vscode/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/prettier/prettier-vscode/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/prettier/prettier-vscode/languages',
      stargazers_url: 'https://api.github.com/repos/prettier/prettier-vscode/stargazers',
      contributors_url: 'https://api.github.com/repos/prettier/prettier-vscode/contributors',
      subscribers_url: 'https://api.github.com/repos/prettier/prettier-vscode/subscribers',
      subscription_url: 'https://api.github.com/repos/prettier/prettier-vscode/subscription',
      commits_url: 'https://api.github.com/repos/prettier/prettier-vscode/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/prettier/prettier-vscode/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/prettier/prettier-vscode/comments{/number}',
      issue_comment_url: 'https://api.github.com/repos/prettier/prettier-vscode/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/prettier/prettier-vscode/contents/{+path}',
      compare_url: 'https://api.github.com/repos/prettier/prettier-vscode/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/prettier/prettier-vscode/merges',
      archive_url: 'https://api.github.com/repos/prettier/prettier-vscode/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/prettier/prettier-vscode/downloads',
      issues_url: 'https://api.github.com/repos/prettier/prettier-vscode/issues{/number}',
      pulls_url: 'https://api.github.com/repos/prettier/prettier-vscode/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/prettier/prettier-vscode/milestones{/number}',
      notifications_url: 'https://api.github.com/repos/prettier/prettier-vscode/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/prettier/prettier-vscode/labels{/name}',
      releases_url: 'https://api.github.com/repos/prettier/prettier-vscode/releases{/id}',
      deployments_url: 'https://api.github.com/repos/prettier/prettier-vscode/deployments',
      created_at: '2017-01-10T19:34:28Z',
      updated_at: '2024-03-23T18:26:10Z',
      pushed_at: '2024-03-25T11:07:38Z',
      git_url: 'git://github.com/prettier/prettier-vscode.git',
      ssh_url: 'git@github.com:prettier/prettier-vscode.git',
      clone_url: 'https://github.com/prettier/prettier-vscode.git',
      svn_url: 'https://github.com/prettier/prettier-vscode',
      homepage: 'https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode',
      size: 105104,
      stargazers_count: 5008,
      watchers_count: 5008,
      language: 'TypeScript',
      has_issues: true,
      has_projects: false,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      has_discussions: true,
      forks_count: 444,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 51,
      license: {
        key: 'mit',
        name: 'MIT License',
        spdx_id: 'MIT',
        url: 'https://api.github.com/licenses/mit',
        node_id: 'MDc6TGljZW5zZTEz',
      },
      allow_forking: true,
      is_template: false,
      web_commit_signoff_required: false,
      topics: [
        'formatter',
        'typescript',
        'visual-studio-code',
        'visual-studio-code-extension',
      ],
      visibility: 'public',
      forks: 444,
      open_issues: 51,
      watchers: 5008,
      default_branch: 'main',
      score: 1,
    },
    {
      id: 78492853,
      node_id: 'MDEwOlJlcG9zaXRvcnk3ODQ5Mjg1Mw==',
      name: 'wux-weapp',
      full_name: 'wux-weapp/wux-weapp',
      private: false,
      owner: {
        login: 'wux-weapp',
        id: 40567621,
        node_id: 'MDEyOk9yZ2FuaXphdGlvbjQwNTY3NjIx',
        avatar_url: 'https://avatars.githubusercontent.com/u/40567621?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/wux-weapp',
        html_url: 'https://github.com/wux-weapp',
        followers_url: 'https://api.github.com/users/wux-weapp/followers',
        following_url: 'https://api.github.com/users/wux-weapp/following{/other_user}',
        gists_url: 'https://api.github.com/users/wux-weapp/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/wux-weapp/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/wux-weapp/subscriptions',
        organizations_url: 'https://api.github.com/users/wux-weapp/orgs',
        repos_url: 'https://api.github.com/users/wux-weapp/repos',
        events_url: 'https://api.github.com/users/wux-weapp/events{/privacy}',
        received_events_url: 'https://api.github.com/users/wux-weapp/received_events',
        type: 'Organization',
        site_admin: false,
      },
      html_url: 'https://github.com/wux-weapp/wux-weapp',
      description: ':dog: 一套组件化、可复用、易扩展的微信小程序 UI 组件库',
      fork: false,
      url: 'https://api.github.com/repos/wux-weapp/wux-weapp',
      forks_url: 'https://api.github.com/repos/wux-weapp/wux-weapp/forks',
      keys_url: 'https://api.github.com/repos/wux-weapp/wux-weapp/keys{/key_id}',
      collaborators_url: 'https://api.github.com/repos/wux-weapp/wux-weapp/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/wux-weapp/wux-weapp/teams',
      hooks_url: 'https://api.github.com/repos/wux-weapp/wux-weapp/hooks',
      issue_events_url: 'https://api.github.com/repos/wux-weapp/wux-weapp/issues/events{/number}',
      events_url: 'https://api.github.com/repos/wux-weapp/wux-weapp/events',
      assignees_url: 'https://api.github.com/repos/wux-weapp/wux-weapp/assignees{/user}',
      branches_url: 'https://api.github.com/repos/wux-weapp/wux-weapp/branches{/branch}',
      tags_url: 'https://api.github.com/repos/wux-weapp/wux-weapp/tags',
      blobs_url: 'https://api.github.com/repos/wux-weapp/wux-weapp/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/wux-weapp/wux-weapp/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/wux-weapp/wux-weapp/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/wux-weapp/wux-weapp/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/wux-weapp/wux-weapp/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/wux-weapp/wux-weapp/languages',
      stargazers_url: 'https://api.github.com/repos/wux-weapp/wux-weapp/stargazers',
      contributors_url: 'https://api.github.com/repos/wux-weapp/wux-weapp/contributors',
      subscribers_url: 'https://api.github.com/repos/wux-weapp/wux-weapp/subscribers',
      subscription_url: 'https://api.github.com/repos/wux-weapp/wux-weapp/subscription',
      commits_url: 'https://api.github.com/repos/wux-weapp/wux-weapp/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/wux-weapp/wux-weapp/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/wux-weapp/wux-weapp/comments{/number}',
      issue_comment_url: 'https://api.github.com/repos/wux-weapp/wux-weapp/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/wux-weapp/wux-weapp/contents/{+path}',
      compare_url: 'https://api.github.com/repos/wux-weapp/wux-weapp/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/wux-weapp/wux-weapp/merges',
      archive_url: 'https://api.github.com/repos/wux-weapp/wux-weapp/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/wux-weapp/wux-weapp/downloads',
      issues_url: 'https://api.github.com/repos/wux-weapp/wux-weapp/issues{/number}',
      pulls_url: 'https://api.github.com/repos/wux-weapp/wux-weapp/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/wux-weapp/wux-weapp/milestones{/number}',
      notifications_url: 'https://api.github.com/repos/wux-weapp/wux-weapp/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/wux-weapp/wux-weapp/labels{/name}',
      releases_url: 'https://api.github.com/repos/wux-weapp/wux-weapp/releases{/id}',
      deployments_url: 'https://api.github.com/repos/wux-weapp/wux-weapp/deployments',
      created_at: '2017-01-10T03:12:26Z',
      updated_at: '2024-03-25T11:06:03Z',
      pushed_at: '2024-03-21T10:56:33Z',
      git_url: 'git://github.com/wux-weapp/wux-weapp.git',
      ssh_url: 'git@github.com:wux-weapp/wux-weapp.git',
      clone_url: 'https://github.com/wux-weapp/wux-weapp.git',
      svn_url: 'https://github.com/wux-weapp/wux-weapp',
      homepage: 'https://wuxui.com',
      size: 49036,
      stargazers_count: 4961,
      watchers_count: 4961,
      language: 'JavaScript',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: true,
      has_discussions: false,
      forks_count: 875,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 27,
      license: {
        key: 'mit',
        name: 'MIT License',
        spdx_id: 'MIT',
        url: 'https://api.github.com/licenses/mit',
        node_id: 'MDc6TGljZW5zZTEz',
      },
      allow_forking: true,
      is_template: false,
      web_commit_signoff_required: false,
      topics: [
        'bem-css',
        'mini-program',
        'miniprogram',
        'ui-design',
        'weapp',
        'weapp-demo',
        'wechat-weapp',
        'weixin',
        'wux',
        'wux-weapp',
        'wuxui',
        'wx-component',
        'wxapp',
      ],
      visibility: 'public',
      forks: 875,
      open_issues: 27,
      watchers: 4961,
      default_branch: 'master',
      score: 1,
    },
  ],
  shrinkData: [
    {
      id: 78483432,
      name: 'TranslucentTB',
      url: 'https://github.com/TranslucentTB/TranslucentTB',
      description: 'A lightweight utility that makes the Windows taskbar translucent/transparent.',
      stargazers_count: 13996,
      language: 'C++',
      isStarred: false,
    },
    {
      id: 78544867,
      name: 'awesome-github-wechat-weapp',
      url: 'https://github.com/opendigg/awesome-github-wechat-weapp',
      description: '微信小程序开源项目库汇总',
      stargazers_count: 8679,
      language: null,
      isStarred: false,
    },
    {
      id: 78494737,
      name: 'walle',
      url: 'https://github.com/Meituan-Dianping/walle',
      description: 'Android Signature V2 Scheme签名下的新一代渠道包打包神器',
      stargazers_count: 6699,
      isStarred: false,
      language: 'Java',
    },
    {
      id: 78566876,
      name: 'prettier-vscode',
      description: 'Visual Studio Code extension for Prettier',
      url: 'https://github.com/prettier/prettier-vscode',
      language: 'TypeScript',
      stargazers_count: 5008,
      isStarred: false,
    },
    {
      id: 78492853,
      name: 'wux-weapp',
      url: 'https://github.com/wux-weapp/wux-weapp',
      description: ':dog: 一套组件化、可复用、易扩展的微信小程序 UI 组件库',
      isStarred: false,
      language: 'JavaScript',
      stargazers_count: 4961,
    },
  ],
  defaultItem: {
    id: 78483432,
    name: 'TranslucentTB',
    url: 'https://github.com/TranslucentTB/TranslucentTB',
    description: 'A lightweight utility that makes the Windows taskbar translucent/transparent.',
    stargazers_count: 13996,
    language: 'C++',
    isStarred: false,
  },
  starredItem: {
    id: 78483432,
    name: 'TranslucentTB',
    url: 'https://github.com/TranslucentTB/TranslucentTB',
    description: 'A lightweight utility that makes the Windows taskbar translucent/transparent.',
    stargazers_count: 13996,
    language: 'C++',
    isStarred: true,
  },
  shrinkDataWithoutEntry: [
    {
      id: 78544867,
      name: 'awesome-github-wechat-weapp',
      url: 'https://github.com/opendigg/awesome-github-wechat-weapp',
      description: '微信小程序开源项目库汇总',
      stargazers_count: 8679,
      language: null,
      isStarred: false,
    },
    {
      id: 78494737,
      name: 'walle',
      url: 'https://github.com/Meituan-Dianping/walle',
      description: 'Android Signature V2 Scheme签名下的新一代渠道包打包神器',
      stargazers_count: 6699,
      isStarred: false,
      language: 'Java',
    },
    {
      id: 78566876,
      name: 'prettier-vscode',
      description: 'Visual Studio Code extension for Prettier',
      url: 'https://github.com/prettier/prettier-vscode',
      language: 'TypeScript',
      stargazers_count: 5008,
      isStarred: false,
    },
    {
      id: 78492853,
      name: 'wux-weapp',
      url: 'https://github.com/wux-weapp/wux-weapp',
      description: ':dog: 一套组件化、可复用、易扩展的微信小程序 UI 组件库',
      isStarred: false,
      language: 'JavaScript',
      stargazers_count: 4961,
    },
  ],
  newItem: {
    id: 7849477,
    name: 'walle',
    url: 'https://github.com/Meituan-Dianping/walle',
    description: 'Android Signature V2 Scheme签名下的新一代渠道包打包神器',
    stargazers_count: 6699,
    isStarred: false,
    language: 'Java',
  },
};

repositorySet.starredData = repositorySet.shrinkData.map((repo: RepositoryType) => ({ ...repo, isStarred: true }));

const mockedLanguage = 'HTML';
const mockedUrls = {
  withoutLang: 'https://api.github.com/search/repositories?q=created:2017-01-10&sort=stars&order=desc',
  withLang: `https://api.github.com/search/repositories?q=created:2017-01-10+language:${mockedLanguage}&sort=stars&order=desc`,
};

const languageList = new Set(['C++', 'Java', 'TypeScript', 'JavaScript']);

enum FETCH_STATUS {
  resolve = 'resolve',
  reject = 'reject',
}

const localStorageDataMock: { [index: string]: any } = {
  [STARRED_REPOSITORIES]: repositorySet.starredData,
  secondEntry: [{ key: 56, id: 454 }],
  thirdEntry: [{ key: 12, id: 8765 }],
};

export {
  mockedLanguage,
  mockedUrls,
  FETCH_STATUS,
  localStorageDataMock,
  languageList,
  repositorySet,
};
